config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }

  resources :boards
  resources :posts do
    member do
      post 'comment'
    end
  end


  get 'static_pages/help'
  get 'static_pages/about'
  root "boards#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :posts
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true
  validates :posts, length: { minimum: 1 }, allow_blank: true

  def close_board
    update_attribute(:activated, false)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :board
  default_scope -> { order(created_at: :asc) }

  validates :user_id, presence: true
  validates :board_id, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destory]
  before_action :start_user, only: [:edit]

  def index
    @activated_boards = Board.where(activated: true)
    @unactivated_boards = Board.where(activated: false)
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(title: board_params[:title], user_id: current_user.id)
    if @board.save
      current_user.posts.create(content: board_params[:post], board_id: @board.id)
      flash[:notice] = "board created"
      redirect_to board_path(@board.id)
    else
      flash.now[:alert] = "empty board name"
      render 'new', status: :unprocessable_entity
    end
  end

  def show
    @board = Board.find(params[:id])
    @posts = @board.posts

    @post = @board.posts.build
  end

  def edit
    @board = Board.find(params[:id])
    @posts = @board.posts
  end

  def destroy
    @board = Board.find(params[:id])
    @board.close_board
    flash[:notice] = 'This board is closed'

    redirect_to edit_board_path(@board)
  end

  private
  def board_params
    params.require(:board).permit(:title, :post)
  end

  def start_user
    @board = Board.find(params[:id])
    if @board.user_id != current_user.id
      flash[:alert] = "You cannot edit this board."
      redirect_to @board, status: :see_other
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "post created"
      redirect_to @post.board
    else
      render 'boards/show', status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to request.referer || root_url
  end

  def comment
    @post = Post.find(params[:id])
    @comment = params[:posts][:comment]
    @post.update(comment: @comment)

    redirect_to request.referer || root_url
  end

  private
  def post_params
    params.require(:post).permit(:content, :board_id)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    p "こんにちは"
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/boards/edit.html.erb
<%= button_to 'Close this board', board_path(@board), method: :delete, class: 'btn' %>

<ol class="posts">
  <% @posts.each do |post| %>
  <li id="post-<%= post.id %>">
    <div class="inner">
      <div class="content"><%= post.content %></div>
      <div class="comment"><%= post.comment %></div>
    </div>

    <span>
      <%= button_to "delete", post_path(post), method: "delete", class: "btn" %>
      <%= form_with(url: comment_post_path(post), scope: :posts) do |f| %>
        <%= f.text_area :comment %>
        <%= f.submit "Add Comment", class: "btn" %>
      <% end %>
    </span>
  </li>
  <% end %>
</ol>

app/views/boards/index.html.erb
<%= link_to 'New Board', new_board_path, class: 'btn btn-primary' %>

<h2>投稿可能なボード</h2>
<ul>
  <% @activated_boards.each do |board| %>
    <li><%= link_to board.title, board, class: 'link' %></li>
  <% end %>
</ul>

<h2>アーカイブ</h2>
<ul>
  <% @unactivated_boards.each do |board| %>
    <li><%= link_to board.title, board, class: 'link' %></li>
  <% end %>
</ul>

app/views/boards/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @board) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :post %>
      <%= f.text_field :post, class: 'form-control' %>

      <%= f.submit "Create Board", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/boards/show.html.erb
<h1><%= @board.title %></h1>

<ol class="posts">
  <%= render @posts %>
</ol>

<% if @board.activated%>
  <%= form_with(model: @post) do |f| %>
    <%= f.hidden_field :board_id, value: @board.id %>
    
    <div class="field">
      <%= f.text_area :content %>
    </div>

    <%= f.submit "Post", class: "btn btn-primary" %>
  <% end %>

  <%= link_to 'edit', edit_board_path(@board), class: 'link' %>
<% else %>
  <ol class="posts">
  <% @posts.each do |post| %>
  <li id="post-<%= post.id %>">
    <div class="inner">
      <div class="content"><%= post.content %></div>
      <div class="comment"><%= post.comment %></div>
    </div>
  </li>
  <% end %>
  </ol>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <%= link_to "Board", '#', id: "logo" %>
  <nav>
    <div class="navbar-header">
      <button id="hamburger" type="button" class="navbar-toggle collapsed">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <ul id="navbar-menu" class="nav navbar-nav navbar-right collapse navbar-collapse">
      <li><%= link_to "Boards",  boards_path %></li>
      <li><%= link_to "About", static_pages_about_path %></li>
      
      <% if user_signed_in? %>
        <li><%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete } %></li>
        <li><%= link_to "Edit", edit_user_registration_path %></li>
      <% else %>
        <li><%= link_to "Log in", new_user_session_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBoard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <%= post.content %>
  
</li>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Welcome to my-Board</h1>
<%= render template: "boards/index" %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>